/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/permit-checker`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/forms` | `/forms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/knowledge` | `/knowledge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/translate` | `/translate`; params?: Router.UnknownInputParams; } | { pathname: `/knowledge/hse`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/forms/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/knowledge/[categoryId]`, params: Router.UnknownInputParams & { categoryId: string | number; } } | { pathname: `/knowledge/hse/[sectionId]`, params: Router.UnknownInputParams & { sectionId: string | number; } } | { pathname: `/knowledge/topic/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/permit-checker`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/forms` | `/forms`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/knowledge` | `/knowledge`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/translate` | `/translate`; params?: Router.UnknownOutputParams; } | { pathname: `/knowledge/hse`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/forms/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/knowledge/[categoryId]`, params: Router.UnknownOutputParams & { categoryId: string; } } | { pathname: `/knowledge/hse/[sectionId]`, params: Router.UnknownOutputParams & { sectionId: string; } } | { pathname: `/knowledge/topic/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/permit-checker${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/forms${`?${string}` | `#${string}` | ''}` | `/forms${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/knowledge${`?${string}` | `#${string}` | ''}` | `/knowledge${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/translate${`?${string}` | `#${string}` | ''}` | `/translate${`?${string}` | `#${string}` | ''}` | `/knowledge/hse${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/permit-checker`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/forms` | `/forms`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/knowledge` | `/knowledge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/translate` | `/translate`; params?: Router.UnknownInputParams; } | { pathname: `/knowledge/hse`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/forms/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/knowledge/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/knowledge/hse/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/knowledge/topic/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/forms/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/knowledge/[categoryId]`, params: Router.UnknownInputParams & { categoryId: string | number; } } | { pathname: `/knowledge/hse/[sectionId]`, params: Router.UnknownInputParams & { sectionId: string | number; } } | { pathname: `/knowledge/topic/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
